name: CookieMoney
version: 0.03
main: me.gastherr.cookiemoney.CookieMoney
authors: [gastherr]
commands:
  cookies:
    description: otwiera panel konta ciastek
  cookie:
    description: otwiera panel konta ciastek